### ISSUE TITLE
Orchestrate Apache Spark YAML Bug Fix

### ISSUE THREAD

**Issue by ghunkins** [sigopt/sigopt-examples#111]
I tried to open PR to put out a tiny bug-fix for the file [`orchestrate/apache_spark/orchestrate.yml`](https://github.com/sigopt/sigopt-examples/blob/master/orchestrate/apache_spark/orchestrate.yml), but I got a `<403>` when I tried to push the branch. 🔒So I'll just post it here!

The following line:

```yaml
repository: orchestrate/spark-example
```
should be replaced with
```yaml
aws:
  ecr:
    repository: orchestrate/spark-example
```
After that example works brilliantly. 🎉 

cc: @alexandraj777 @benhsu75 @dclayh

**Comment by ghunkins** [comment]
For reference, here's the stack-trace without the fix.

```
(sigopt) Gregorys-MBP-2:apache_spark ghunkins$ sigopt run -f orchestrate.yml
Containerizing your model and starting your experiment, this may take a few minutes...
Traceback (most recent call last):
  File "/Users/ghunkins/anaconda3/envs/sigopt/bin/sigopt", line 11, in <module>
    sys.exit(main())
  File "/Users/ghunkins/anaconda3/envs/sigopt/lib/python3.5/site-packages/orchestrate/core/main.py", line 565, in main
    app.run()
  File "/Users/ghunkins/anaconda3/envs/sigopt/lib/python3.5/site-packages/cement/core/foundation.py", line 882, in run
    return_val = self.controller._dispatch()
  File "/Users/ghunkins/anaconda3/envs/sigopt/lib/python3.5/site-packages/cement/ext/ext_argparse.py", line 918, in _dispatch
    return func()
  File "/Users/ghunkins/anaconda3/envs/sigopt/lib/python3.5/site-packages/orchestrate/core/cement_utils.py", line 36, in impl
    return func(self, *args, **kwargs)
  File "/Users/ghunkins/anaconda3/envs/sigopt/lib/python3.5/site-packages/orchestrate/core/main.py", line 135, in run
    experiment_id = self.runner(local=False, quiet=quiet)
  File "/Users/ghunkins/anaconda3/envs/sigopt/lib/python3.5/site-packages/orchestrate/core/main.py", line 53, in runner
    self.app.services.options_validator_service.validate_orchestrate_options(**options)
TypeError: validate_orchestrate_options() got an unexpected keyword argument 'repository'
```

**Comment by alexandraj777** [comment]
Hey @ghunkins, thanks you for bringing up this issue. Thank you as well for including `pip show orchestrate`, that was really helpful! 

You're working with Orchestrate version `0.2.4`. For your version of Orchestrate, you should be using the `aws.ecr.repository` field, as you have described correctly in your fix. 

However, I'd recommend upgrading your version of Orchestrate, which you can do by running:
```bash
pip install --upgrade orchestrate
```
As of version `0.2.7`, Orchestrate supports two ways of providing a repository name, the `aws.ecr.repository` method, and `repository` method. We're planning to move over to just `repository` in version `0.3.0`. If you upgrade your client to the latest version of Orchestrate, you can get started using the new field.

Happy optimizing!

**Comment by ghunkins** [comment]
Figured it out @alexandraj777: I figured it was a version issue, but didn't know exactly where it was stemming from. Turns out that the latest version for `python3.5` is `0.2.4`. 

```
(sigopt) Gregorys-MBP-2:example ghunkins$ python --version
Python 3.5.6 :: Anaconda, Inc.
(sigopt) Gregorys-MBP-2:example ghunkins$ pip install orchestrate==0.2.7
Collecting orchestrate==0.2.7
  Could not find a version that satisfies the requirement orchestrate==0.2.7 (from versions: 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.1.8, 0.2.0, 0.2.3, 0.2.4)
No matching distribution found for orchestrate==0.2.7
```

After switching to a `python3.6` environment, I was able to successfully install `0.2.7`, so there's a hard dependency there. 

After that it's smooth sailing. ⛵️Thanks for the help!
